%%Test
clear;
clc;
close all;

switch 2
    case 1
        obj= Algorithms('2','New');
        obj.Data.minREP.B_feeder=[3;2]*1;
        obj.Data.minEV.Pmax_ev=3;
        obj.Data.minResident.omega_re=20;
        
        Solve_ALL(obj)
        % save('testpevmax1p5beta3.mat','obj')
        % save('testpevmax1p5beta2p4.mat','obj')
%         save('testpevmax1p5beta30.mat','obj')
        
        %  save('testpevmax1p5beta5.mat','obj')
        %  save('testpevmax3beta5.mat','obj')
        %  save('testpevmax10beta5.mat','obj')
        
        save('testpevmax10beta30.mat','obj')
        draw(obj,10)
        drawSOC(obj,11)
    case 2
        load('testpevmax1p5beta2p4.mat','obj')
        draw(obj,1)
        load('testpevmax1p5beta3.mat','obj')
        draw(obj,2)
        load('testpevmax1p5beta30.mat','obj')
        draw(obj,3)
        
        
        load('testpevmax1p5beta5.mat','obj')
        draw(obj,4)
        load('testpevmax3beta5.mat','obj')
        draw(obj,5)
        load('testpevmax10beta5.mat','obj')
        draw(obj,6)
end

function draw(obj,k)
figure(k)
time=(1:48)/2;
hold on;
plot(time,obj.PevT(1,:),'r+')
plot(time,obj.PbuyT(1,:),'r-')
plot(time,obj.PevT(2,:),'bo')
plot(time,obj.PbuyT(2,:),'b-')
plot(time,obj.PevT(1,:)+obj.PbuyT(1,:),'r-','LineWidth',1.5)
plot(time,obj.PevT(2,:)+obj.PbuyT(2,:),'b-','LineWidth',1.5)
plot(time,obj.PevT(1,:)+obj.PbuyT(1,:)+obj.PevT(2,:)+obj.PbuyT(2,:),'g-','LineWidth',1.5)
hold off;
legend('Pev1','Pbuy1','Pev2','Pbuy2','Pev1+Pbuy1','Pev2+Pbuy2(feeder2)','Pev1+Pbuy1+Pev2+Pbuy2(feeder1)')
xlabel('time(h)');ylabel('power(kW)')
b1=num2str(obj.Data.minREP.B_feeder(1));
b2=num2str(obj.Data.minREP.B_feeder(2));
Pmax_ev=num2str(obj.Data.minEV.Pmax_ev);
title(strcat('  Pmax of ev=',Pmax_ev,'  \beta_1=',b1,'  \beta_2=',b2))
box on
end
function drawSOC(obj,k)
figure(k)
time=(0:48)/2;
hold on;
plot(time,obj.Data.BPVL.SOC(1,:))
plot(time,obj.Data.BPVL.SOC_of_EV(1,:))
hold off;
legend('SOC of Bat','SOC of EV')
end


% figure(k+2)
% hold on;
% plot(time,sum(obj.Data.BPVL.GG),'g-','LineWidth',1.5)
% plot(time,sum(obj.Data.BPVL.GC),'k--','LineWidth',1.5)
% plot(time,obj.Data.BPVL.GG(1,:),'ro')
% plot(time,obj.Data.BPVL.GC(1,:),'r+')
% plot(time,obj.Data.BPVL.GG(2,:),'bo')
% plot(time,obj.Data.BPVL.GC(2,:),'b+')
% hold off;
% xlabel('time(h)');ylabel('power(kW)')
% legend('PV1+PV2','Load1+Load2','PV1','Load1','PV2','Load2')
% title('Total power generated by PV and total consumption by users')
%
%
% figure(k+3)
% % Resident
% hold on;
% plot(time,obj.Data.BPVL.GC(1,:),'og')% demand
% plot(time,obj.PbuyT(1,:)+obj.Data.BPVL.GG2user(1,:)+obj.PbatT(1,:),'g')
% % plot(obj.Data.BPVL.GG(1,:)+obj.PbuyT(1,:)...
% %     +obj.PevT(1,:)-obj.PbatT(1,:)-...
% %     obj.Data.BPVL.GC(1,:),'+')
% grid on
% hold off
% xlabel('time(h)');ylabel('power(kW)')
% legend('demand','supply')
% title('The power demanded by user 1 and the power provided to user 1 by the algorithm')
%
%

